base:
  project: wine-quality-prediction
  random_state: 42
  target_col: TARGET

data_source:
  remote_source: data/remote/winequality.csv
  local_source: data/raw/winequality.csv

split_data:
  train_data: data/processed/train_winequality.csv
  test_data: data/processed/test_winequality.csv
  test_size: 0.2

estimators:
  ElasticNet:
    params:
      alpha: 0.88
      l1_ratio: 0.89

reports:
  params: reports/params.json
  scores: reports/scores.json

model_dir: models
